# Meta Data for SEO

## Homepage
title = "Daptin"
titleSeparator = "-"
titleAddition = "Backend server"
description = "Daptin is a backend server for building applications"

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["daptin.png"]
ogLocale = "en_US"
domainTLD = "daptin.github.io"
titleHome = "Daptin Server"

## Twitter Cards
twitterSite = "@daptin"
twitterCreator = "@phparth"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Daptin"
schemaAuthor = "Parth Mudgal"
schemaAuthorTwitter = "https://twitter.com/phparth"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/parth.mudgal/"
schemaAuthorGitHub = "https://github.com/artpar"
schemaLocale = "en-US"
schemaLogo = "logo-daptin.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/daptin"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/daptin/daptin"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> and <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2020-2022 Parth Mudgal"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Daptin server. <a class=\"alert-link stretched-link\" href=\"https://github.com/daptin/daptin/releases/\">Check out Daptin v0.9.8</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/daptin/daptin"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
